//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chatter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image_Table
    {
        public int imgID { get; set; }
        public string userImg { get; set; }
        public string userID { get; set; }
    }
}
